---
title: "MRAID for one sample MR"
author: "Frederick J. Boehm"
date: "`r Sys.Date()`"
output: bookdown::html_document2
---


# Overview

We want to change the MRAID model so that it accommodates one-sample MR. MRAID was designed for two-sample MR, but, by allowing for correlation between the two error terms, we can adapt it to one-sample MR.


# Model Specification

$$x = Z\beta + \epsilon$$

$$y = Z\beta\alpha + Z(\beta \circ v)\rho + Z\eta_u + \epsilon_y$$

We also specify the distributions for the entries in the length $p$ vectors.

$$\beta[j] \sim \pi_{\beta}N(0, \sigma^2_{\beta}) + (1 - \pi_{\beta})\delta_0$$

$$\eta_u[j] \sim \pi_1 N(0, \sigma^2_{\eta}) + (1 - \pi_1) \delta_0$$

$$\eta_u[j] \sim \pi_0N(0, \sigma^2_{\eta}) + (1 - \pi_0)\delta_0$$

$$p(v[j] = 1) = \pi_c$$ if $\beta[j] \neq 0$


Other specifications are described in the supplementary text for Zhongshang's paper.



# Detailed sampling steps - when not using summary statistics

$$f(\alpha, \beta, \gamma, \eta_u, \tau, v, \rho, \Gamma |x,y) \propto f(x, y | \alpha, \beta, \gamma, \eta_u, \tau, v, \rho, \Gamma)f(\beta|\gamma)f(\eta_u|\tau)f(v|\gamma)f(\tau|\gamma) f(\gamma|\pi_{\beta}) f(\pi_{\beta}) f(\pi_1) f(\pi_0) f(\pi_C)f(\Gamma)$$
and $$f(x, y | \alpha, \beta, \gamma, \eta_u, \tau, v, \rho, \Gamma) = $$

# Examining the update for $\beta[j]$

Working from the supplemental materials for Yuan et al. 2022, we need to consider the distribution $f(vec(X)|\alpha, \beta, \gamma, \eta_u, \tau, v, \rho)$, where $X$ is a n by 2 matrix of the two traits, y and x, and the parameters are as defined by Yuan et al. 

# MRAID with summary statistics

The R and C++ code require inputs as summary statistics, so a user must acquire 
summary statistics in the form of SNP correlation matrix and SNP effect size estimates.

One approach would involve using GEMMA to get summary statistics, if, for example, 
one is working with individual-level UKB data.






